---
- name: Verificar se Docker está instalado
  ansible.builtin.command: which docker
  register: docker_instalado
  ignore_errors: yes

- name: Baixar script de instalação do Docker
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: docker_instalado.rc != 0

- name: Executar script de instalação do Docker
  ansible.builtin.shell: /tmp/get-docker.sh
  args:
    executable: /bin/bash
  when: docker_instalado.rc != 0

- name: Adicionar usuário atual ao grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Fazer pull apenas das imagens apache e nginx
  ansible.builtin.command:
    cmd: >
      docker compose -f {{ ansible_user_dir }}/.scripts/docker-apps/docker-compose.yml pull

- name: Subir containers syncthing e stirling-pdf
  ansible.builtin.command:
    cmd: >
      docker compose -f {{ ansible_user_dir }}/.scripts/docker-apps/docker-compose.yml up -d syncthing stirling-pdf
