---
- name: Configurar GRUB para não esperar
  hosts: localhost
  become: true
  tasks:

    - name: Fazer backup do arquivo grub
      copy:
        src: /etc/default/grub
        dest: /etc/default/grub.bak
        remote_src: yes
        backup: yes

    - name: Ajustar GRUB_TIMEOUT
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: 'GRUB_TIMEOUT=0'
        create: yes
        backup: yes

    - name: Ajustar GRUB_TIMEOUT_STYLE
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT_STYLE='
        line: 'GRUB_TIMEOUT_STYLE=hidden'
        create: yes
        backup: yes

    - name: Ajustar GRUB_DISABLE_RECOVERY
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_DISABLE_RECOVERY='
        line: 'GRUB_DISABLE_RECOVERY=true'
        create: yes
        backup: yes

    - name: Atualizar GRUB
      command: update-grub
      args:
        warn: false
