---
- name: Pós-instalação Linux Mint
  hosts: localhost
  gather_facts: yes
  become: false

  vars_prompt:
    - name: restic_password
      prompt: "Digite a senha do repositório Restic"
      private: yes

  vars:
    docker_compose_path: "{{ ansible_env.HOME }}/.scripts/docker-apps/docker-compose.yml"
    restic_repo: "/media/restic/restic_notebook_repo"
    pacotes_apt: "{{ lookup('file','pacotes_apt.txt').splitlines() }}"
    pacotes_flatpak: "{{ lookup('file','pacotes_flatpak.txt').splitlines() }}"

  tasks:

    - name: Verifica se restic está instalado
      ansible.builtin.command: restic version
      ignore_errors: yes
      register: restic_check

    - name: Falha se Restic não estiver instalado
      ansible.builtin.fail:
        msg: "Restic não está instalado!"
      when: restic_check.rc != 0

    - name: Restaurar backup Restic
      ansible.builtin.command:
        cmd: restic -r {{ restic_repo }} restore latest --target / --tag mths --tag linux_mint
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"

    - name: Fazer backup do arquivo de mirrors
      become: true
      ansible.builtin.copy:
        src: /etc/apt/sources.list.d/official-package-repositories.list
        dest: /etc/apt/sources.list.d/official-package-repositories.list.disabled
        remote_src: yes

    - name: Substituir URL do repositório Linux Mint
      become: true
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/official-package-repositories.list
        regexp: '^(deb\s+)http://packages\.linuxmint\.com'
        replace: '\1https://mint-packages.c3sl.ufpr.br'

    - name: Substituir URL dos repositórios Ubuntu
      become: true
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/official-package-repositories.list
        regexp: '^(deb\s+)http://archive\.ubuntu\.com/ubuntu'
        replace: '\1http://sft.if.usp.br/ubuntu'

    - name: Habilitar arquitetura i386
      become: true
      ansible.builtin.command: dpkg --add-architecture i386

    - name: Atualizar repositórios e pacotes
      become: true
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes apt
      become: true
      ansible.builtin.apt:
        name: "{{ pacotes_apt }}"
        state: present

    - name: Instalar pacotes Flatpak (como root)
      become: true
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
      loop: "{{ pacotes_flatpak }}"

    - name: Subir containers Docker
      community.docker.docker_compose:
        project_src: "{{ docker_compose_path | dirname }}"
        files:
          - "{{ docker_compose_path | basename }}"
        state: present
