---
- name: Permitir jogos rodarem em fullscreen
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0"
  become: true

- name: Baixar e instalar TeamViewer
  block:
    - ansible.builtin.get_url:
        url: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
        dest: /tmp/teamviewer.deb
    - ansible.builtin.apt:
        deb: /tmp/teamviewer.deb
        state: present
  become: true

- name: Baixar e instalar oh-my-posh
  ansible.builtin.get_url:
    url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64"
    dest: /usr/local/bin/oh-my-posh
    mode: '0755'
  become: true

- name: Baixar script Tailscale
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/tailscale_install.sh
    mode: '0755'

- name: Executar script Tailscale
  ansible.builtin.shell: /tmp/tailscale_install.sh
  become: true

- name: Atualizar tldr usando zsh com ativação do venv
  ansible.builtin.shell: |
    source /home/mths/.scripts/python3-venv/bin/activate
    tldr --update
  args:
    executable: /usr/bin/zsh

- name: Carregar configurações do dconf
  ansible.builtin.shell: |
    dconf load / < {{ ansible_user_dir }}/.dconf/dconf

- name: Configurar qBittorrent como app padrão de magnet
  ansible.builtin.command: xdg-mime default org.qbittorrent.qBittorrent.desktop x-scheme-handler/magnet

- name: Definir zsh como shell padrão
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
